Vagrant.configure("2") do |config|

  config.vagrant.plugins = ["vagrant-hostsupdater", "vagrant-vbguest"]

  LOCAL_NETWORK = ENV['LOCAL_NETWORK'] || "192.168.10.10"
  LOCAL_HOSTNAME = ENV['LOCAL_HOSTNAME'] || "flumen.k8s"
  LOCAL_PROJECT_FOLDER = ENV['LOCAL_PROJECT_FOLDER'] || "../"

  config.vm.box = "generic/ubuntu1804"

  config.vm.define "flumen" do |flumen|

    config.vm.synced_folder LOCAL_PROJECT_FOLDER, "/flumen"
    config.vm.network "private_network", ip: LOCAL_NETWORK
    config.vm.hostname = LOCAL_HOSTNAME

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Flumen"

        vb.memory = "4024"
        vb.cpus = "2"
    end

  end

  config.vm.provision "containers", type: "shell", path: "infra/containers/provision.sh", args: []
  config.vm.provision "kubeadm", type: "shell", path: "infra/kubeadm/provision.sh", args: []
  config.vm.provision "kubectl", type: "shell", path: "infra/kubectl/provision.sh", args: []

  config.vm.provision "helm", type: "shell", path: "infra/helm/provision.sh", args: []
  config.vm.provision "traefik", type: "shell", path: "infra/traefik/provision.sh", args: [LOCAL_NETWORK]

  config.vm.provision "dashboard", type: "shell", path: "infra/dashboard/provision.sh", args: []

end
