apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controllers.flumen.com
spec:
  group: flumen.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            namespaces:
              type: array
              items:
                type: string
            selector:
              type: string
  scope: Namespaced
  names:
    plural: controllers
    singular: controller
    kind: FlumenController
    shortNames:
      - fc
