apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: migrations.flumen.com
spec:
  group: flumen.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                image:
                  type: string
  scope: Namespaced
  names:
    plural: migrations
    singular: migration
    kind: FlumenMigration
    shortNames:
      - fm
